"""
End-to-End Test for Local Legal RAG: FAISS + all-MiniLM-L6-v2 + Ollama
"""
import asyncio
import json
import os
import sys
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config.settings import settings
from src.core.indexer.faiss_client import FAISSClient
from src.core.embedding.local_embedder import LocalEmbedder
from src.core.llm.ollama_client import OllamaClient
from src.core.retrieval.hybrid_retriever import HybridRetriever
from src.core.retrieval.query_rewriter import QueryRewriter


async def run_tests():
    print("=" * 60)
    print("1. Testing FAISS Vector Store & HNSW Configuration")
    print("=" * 60)
    faiss_client = FAISSClient()
    info = faiss_client.get_collection_info()
    print(f"Collection Name: {info['name']}")
    print(f"Total Chunks: {info['count']}")
    print(f"Dimension: {info['dimension']}")
    print(f"HNSW Parameters: M={info['hnsw_m']}, efConstruction={info['hnsw_ef_construction']}, efSearch={info['hnsw_ef_search']}")
    assert info['count'] > 0, "No chunks found in FAISS index!"
    assert info['hnsw_m'] == 24, f"Expected M=24, got {info['hnsw_m']}"
    assert info['hnsw_ef_construction'] == 100, f"Expected efC=100, got {info['hnsw_ef_construction']}"
    assert info['hnsw_ef_search'] == 100, f"Expected efS=100, got {info['hnsw_ef_search']}"
    print("✅ FAISS Vector Store verified successfully!")

    print("\n" + "=" * 60)
    print("2. Testing Local Sentence-Transformers Embedder")
    print("=" * 60)
    embedder = LocalEmbedder()
    test_vec = embedder.embed_query("Quelle est la durée du bail ?")
    print(f"Embedding dimension: {len(test_vec)} (expected 384)")
    assert len(test_vec) == 384, f"Expected 384, got {len(test_vec)}"
    print("✅ Embedder verified successfully!")

    print("\n" + "=" * 60)
    print("3. Testing Hybrid Retrieval (Dense FAISS + BM25 RRF)")
    print("=" * 60)
    retriever = HybridRetriever(vector_client=faiss_client, embedder=embedder)
    query = "Quelle est la durée du contrat de bail ?"
    results = await retriever.hybrid_search(query, top_k=3)
    print(f"Query: '{query}'")
    print(f"Retrieved {len(results)} chunks:")
    for idx, r in enumerate(results, start=1):
        print(f"  [{idx}] Score: {r.get('score', 0):.4f} | ID: {r.get('id')} | Text snippet: {r.get('text', '')[:100]}...")
    assert len(results) > 0, "Hybrid search returned 0 results!"
    print("✅ Hybrid retrieval verified successfully!")

    print("\n" + "=" * 60)
    print("4. Testing Local Ollama Connectivity & Query Rewriting")
    print("=" * 60)
    ollama = OllamaClient()
    healthy = ollama.health_check()
    print(f"Ollama Server reachable: {healthy} (model: {settings.OLLAMA_MODEL})")
    if healthy:
        rewriter = QueryRewriter(ollama_client=ollama)
        raw_q = "combien de temps dure le bail ?"
        rewritten_q = await rewriter.rewrite(raw_q)
        print(f"Original: '{raw_q}' -> Rewritten: '{rewritten_q}'")
        print("✅ Query Rewriter verified successfully!")
    else:
        print("⚠️ Ollama is not currently accessible inside sandbox; generation test skipped.")

    print("\n" + "=" * 60)
    print("5. Testing Full RAG Answer Generation (with Citations)")
    print("=" * 60)
    if healthy:
        context_parts = []
        for idx, chunk in enumerate(results, start=1):
            context_parts.append(f"[{idx}] {chunk['text']}")
        context_str = "\n\n".join(context_parts)

        system_prompt = (
            "Vous êtes un assistant juridique strict pour l'analyse de contrats. "
            "Vous devez répondre UNIQUEMENT en utilisant le contexte fourni.\n"
            "Règles strictes :\n"
            "1. CITATION : Citez systématiquement vos sources sous la forme [1], [2] correspondant aux passages du contexte.\n"
            "2. CHIFFRES EXACTS : Copiez les dates, montants (€, %) et durées TEXTUELLEMENT sans les modifier.\n"
            "3. ABSENCE : Si l'information n'est pas dans le contexte, répondez exactement : "
            "'Le contrat ne contient pas d'information sur ce point.' N'inventez rien."
        )

        prompt = f"Contexte du contrat :\n{context_str}\n\nQuestion de l'utilisateur : {query}\n\nRéponse structurée et concise :"
        answer = await ollama.agenerate(prompt=prompt, system=system_prompt, temperature=0.1)
        print(f"\nQuestion: {query}\n\nAnswer generated by Ollama ({settings.OLLAMA_MODEL}):\n")
        print(answer)
        print("\n✅ End-to-end RAG generation verified successfully!")

    print("\n" + "=" * 60)
    print("🎉 ALL LOCAL RAG TESTS PASSED!")
    print("=" * 60)

if __name__ == "__main__":
    asyncio.run(run_tests())

